[workspace]
resolver = "3"
members = [ "argon","library/argon_core"]

[workspace.lints.clippy]
all = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
unwrap_used = "deny"
